#!/usr/bin/ruby

# musicologica.cz misses a rss feed;
# they don't seem to be going to add one (I have asked repeatedly);
# I am used to read the website using a rss reader ...

require 'uri'
require 'net/http'

require 'nokogiri'
require 'nyny'

require_relative '../lib/articles_rss'

module Musicologica
  # knows how to find new articles on the homepage
  class MusicologicaHomepageArticles
    def initialize(uri, document)
      @uri = uri
      @doc = document
    end

    def self.create_articles
      uri = URI('http://www.musicologica.cz/')
      response = Net::HTTP.get_response uri
      doc = Nokogiri::HTML response.body
      articles = new uri, doc
    end

    def each
      article_nodes.each do |article|
        yield ArticlesRSS::Article.new(
                link(article),
                title(article),
                published_at(article)
              )
      end
    end

    def article_nodes
      @doc.css '.article-item-list-allArticle .article-item-list-allArticle-text'
    end

    def link(article)
      href = article.css('h2 a')[0]['href']
      if href.start_with? 'http'
        href
      else
        @uri + href
      end
    end

    def title(article)
      article.css('h2').text.strip
    end

    def published_at(article)
      str = article.css('.date').text.match(/\d+\s*\.\d+\s*\.\d+/)[0].gsub(' ', '')
      Time.strptime(str, '%d.%m.%Y')
    end
  end

  class App < NYNY::Base
    get '/' do
      redirect_to '/musicologica/rss'
    end

    get '/rss' do
      headers['Content-Type'] = ArticlesRSS::RSS_CONTENT_TYPE
      ArticlesRSS.build MusicologicaHomepageArticles.create_articles,
                        feed_uri: request.url,
                        title: 'Musicologica.cz unofficial rss feed',
                        description: 'Feed is generated by an independent application parsing the homepage of musicologica.cz. With love, igneus'
    end
  end
end
